### ISSUE TITLE
Benji Disk Usage

### ISSUE THREAD

**Issue by FreshXOpenSource** [elemental-lf/benji#80]
Hi,

we are running https://github.com/FreshXOpenSource/pve-snapbackup with benji as an underlying tool to generate fully automized snapshot backups in Proxmox / PVE.

The backup box has 36TB storage and the source pools in CEPH have a netto volume of 14TB used space.

Now the used space of the benji backup is increasing more than expected (using 33TB of our backup storage). i wrote i litte script to calculate the complete usage of our initial backups+snapshots which comes to the conclusion, thats benji should only use 11TB.

The script is this

```
DISKSTOTAL=`benji ls | awk -F '|' '{print $4" "$6}'|sort -u|grep -v "^ volume" | sed "s/GiB//" | awk '{sum +=$2} END { print sum*1024}'`
benji -m ls | jq -r '.versions[] | "\(.volume)\t\(.snapshot)\t\(.size/1024/1024/1024) GB\t\(.bytes_written/1024/1024) MB"' | sort -n -k5 | grep $GREP | awk 'BEGIN {sum='$DISKSTOTAL'} {sum += $5; print $0} END {print "Total : "sum/1024" GB"}'
```

First i calculate the initial backups, then i add up all snapshots.

Can you tell me, where am i missing something? or how can i get a "real" numer telling me what the space on our backup storage is used for?

Thanks

**Comment by elemental-lf** [comment]
Oh, nice to see some software based on Benji. Thanks.

Regarding your problem:  

The deal with `bytes_written` is that it really only has significance to the version it is referring to and to the point in time this version was created. Your command will underestimate the used space if deduplication is at work.
Imagine a block that originally was created for a version that has already been deleted since. But this block is still there because it still has one or more versions that are referring to this block. So the original version which accounted this block in `bytes_written` is no longer there but it will show up in `deduplicated_bytes` for each version that still uses it.

Could you please run `benji storage-stats` to see if the used space reported by `df` or `du` matches up with the number reported by Benji? This will take quite some time but it will show us if Benji has lost track of blocks in the storage somehow.

**Comment by FreshXOpenSource** [comment]
Thanks,

benji storage-stats shows

```+---------------+--------------+
| objects_count | objects_size |
+---------------+--------------+
|      17720690 |      33.8TiB |
+---------------+--------------+
```

while the `df` is at

```(benji) root@backy:~# df -h /data/backup/
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/backup-backup01   36T   35T  234G 100% /data/backup
```

The numbers fit so far. What would you suggest to figure out which snapshot consumes what amount of diskspace?

**Comment by elemental-lf** [comment]
See https://github.com/elemental-lf/benji/issues/74 for a discussion why this is hard to do because of global deduplication. As suggested in that issue it might be useful to calculate the usage for a volume (i.e. an aggregate number for all versions of a volume) or for a group volumes. This will always overestimate the usage, depending on how much deduplication is happening by quite a lot. And you cannot really use it as an indicator of how much space would be freed if you delete the volume you just calculated the usage for. I will look into this now as this is the second or third request for such a feature.

**Comment by elemental-lf** [comment]
I've just pushed the code for the new `benji storage-usage` command to master. Some bare-bones documentation is [here](https://benji-backup.me/statistics.html#space-usage-statistics). Please let me know would you think.

**Comment by PandemiK911** [comment]
I'm also to get more stats from storage pool. As we're using docker version of benji, I tried to update the docker image from the hub but it seems the image didn't get updated for 4 months (https://hub.docker.com/r/elementalnet/benji).

I'm still not at ease with docker : is this the correct way to check for new versions ?
Is docker still a supported way to run Benji ? Perhaps don't you have much time to maintain the docker image ?

Thanks !

**Comment by FreshXOpenSource** [comment]
a quick update and a big sorry for the delay, im still fighting with your git version and python3-rados which is not natively available for proxmox/pve6.

Meanwhile i ran a(nother) benji cleanup and my disk usage dropped from 46TB down to 8TB! I guess my first try to run the cleanup was not properly finished.

Still i will checkout the `benji storage-usage` command as soon as i fixed this issue to better understand the usage of our backup solution

**Comment by FreshXOpenSource** [comment]
Hi Lars,

not quite sure how to interpret this data

```
(benji) root@xyz:~# benji storage-usage
    INFO: $ /usr/local/benji/bin/benji storage-usage
+---------------+---------+---------+--------+-----------+------------------------+
| storage       | virtual | sparse  | shared | exclusive | deduplicated_exclusive |
+---------------+---------+---------+--------+-----------+------------------------+
| backup-bank01 | 75.6TiB | 43.9TiB |   0.0B |   31.7TiB |                 7.4TiB |
+---------------+---------+---------+--------+-----------+------------------------+
```

**Comment by elemental-lf** [comment]
Without a filter expression `benji storage-usage` computes the usage over all versions present in the database. These versions have a size of `75.6TiB`, this includes sparse blocks. As the set includes all blocks in the storage there are no shared blocks, that's what the deduplication is there for after all. In the `exclusive` column all non-sparse blocks are accounted for. Blocks that are present in multiple versions are counted multiple times. `deduplicated_exclusive` accounts each unique block only once, it is roughly the amount of storage space used. `sparse + shared + exclusive` equals `virtual`.

`benji storage-usage` is more useful when used with a filter expression. For example by matching on a label that represents the customer a backup versions belongs to: `benji storage-usage 'labels["customer-number"] == "12345678"'`.

**Comment by elemental-lf** [comment]
I'm going to close this issue. If you have additional questions please open a new one. Thanks!
